anonymous_enable=YES
local_enable=NO

write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO

max_clients=200
anon_max_rate=51200
idle_session_timeout=30

listen=YES
listen_ipv6=NO

#anon_root=/srv/ftp
