
# 1. El servidor se iniciará en modo standalone (independiente) usando IPv4.
listen=YES
listen_ipv6=NO

# 2. Mensaje de bienvenida.
ftpd_banner=--- Welcome to the FTP server of 'sistema.sol'---

# 3. Mensaje para usuarios anonimos
dirmessage_enable=YES
anon_root=/srv/ftp

# 4. Puerto 20 para datos 
connect_from_port_20=YES

# 5. Cerrar conexione inactivas > 720s
idle_session_timeout=720

# 6. Maximo 15 conexiones simultaneas
max_clients=15

# 7. Ancho de banda  5 x 1024 x 1024
local_max_rate=5242880

# 8. Ancho de banda usuarios anonimos 2 x 1024 x 1024
anon_max_rate=2097152

# 9.  Permisos usuarios anonimos (solo descarga)
anonymous_enable=YES
write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO

# 10. Permisos usuarios locales (subir y descargar) 
local_enable=YES
write_enable=YES

# 11. Chroot y excepciones
chroot_local_user=YES
allow_writeable_chroot=YES
chroot_list_enable=YES
chroot_list_file=/etc/vsftpd.chroot_list

